require('dotenv').config();
const mongoose = require('mongoose');
const Admin = require('./models/Admin');
const Project = require('./models/Project');

const SAMPLE_PROJECTS = [
  {
    name: 'Adarsh Parkland',
    description: 'Premium residential township by Adarsh Group',
    website: 'https://adarshparkland.com',
    allowedOrigins: ['https://adarshparkland.com', 'https://www.adarshparkland.com'],
  },
  {
    name: 'Sobha Neopolis',
    description: 'World-class township by Sobha Developers',
    website: 'https://sobhaneopolis.co',
    allowedOrigins: ['https://sobhaneopolis.co', 'https://www.sobhaneopolis.co'],
  },
  {
    name: 'Prestige City',
    description: 'Luxury residential project by Prestige Group',
    website: 'https://prestigecity.com',
    allowedOrigins: ['https://prestigecity.com', 'https://www.prestigecity.com'],
  },
  {
    name: 'Brigade Utopia',
    description: 'Smart homes by Brigade Group',
    website: 'https://brigadeutopia.com',
    allowedOrigins: ['https://brigadeutopia.com', 'https://www.brigadeutopia.com'],
  },
];

const slugify = (str) =>
  str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ Connected to MongoDB\n');

  // Create admin
  const existingAdmin = await Admin.findOne({ email: 'admin@realestate.com' });
  if (!existingAdmin) {
    await Admin.create({ name: 'Admin User', email: 'admin@realestate.com', password: 'Admin@123' });
    console.log('✅ Admin created');
    console.log('   Email:    admin@realestate.com');
    console.log('   Password: Admin@123\n');
  } else {
    console.log('ℹ️  Admin already exists\n');
  }

  // Create projects — apiKey auto-generated by model hook
  console.log('📦 Projects & API Keys:');
  console.log('─'.repeat(80));

  for (const p of SAMPLE_PROJECTS) {
    const slug = slugify(p.name);
    let project = await Project.findOne({ slug });

    if (!project) {
      project = await Project.create({ ...p, slug });
      console.log(`✅ Created: ${p.name}`);
    } else {
      console.log(`ℹ️  Exists:  ${p.name}`);
    }

    console.log(`   Slug:            ${project.slug}`);
    console.log(`   API Key:         ${project.apiKey}`);
    console.log(`   Allowed Origins: ${project.allowedOrigins.join(', ')}`);
    console.log('');
  }

  console.log('─'.repeat(80));
  console.log('\n🎉 Seed complete!');
  console.log('👉 Copy each project\'s API Key into that website\'s .env as BLOG_API_KEY=...');
  console.log('👉 Login at http://localhost:3000/login\n');
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
